config/routes.rb
Rails.application.routes.draw do

  get 'sponsored_posts/show'

  get 'sponsored_posts/new'

  get 'sponsored_posts/edit'

  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
    get 'sponsored_posts/show'

    get 'sponsored_posts/new'

    get 'sponsored_posts/edit'
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  default_scope { order('updated_at ASC') }

  after_create :send_favorite_emails

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :labelings
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?

    label_string.split(",").map do |label|
      Label.find_or_create_by(name: label.strip)
    end
  end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :sponsored_posts 

  scope :visible_to, -> (user) { user ? all : where(public: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save { self.role ||= :member }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 100 },
            format: { with: EMAIL_REGEX }

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def has_posts?
    posts.count > 0
  end

  def has_comments?
    comments.count > 0
  end

  def has_favorites?
    favorites.count > 0
  end    
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bloccit #{@user.name}!"
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.visible_to(current_user)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_favorite.html.erb
<div class="media">
  <%= render partial: 'votes/voter', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
      <%= render partial: "labels/list", locals: { labels: post.labels } %>
    </h4>
    <small>
      <%= image_tag User.avatar_url(current_user, 48), class: "gravatar", style: "float: left; margin-top: 5px" %>
      <%= time_ago_in_words(post.created_at) %> ago.
      <br>
      Submitted by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div> 

app/views/users/confirm.html.erb
<h2>Sign Up Confirmation</h2>

<div class="row">
  <div class="col-md-4">
    <h4>Is this information correct?</h4>
    <h5>Email: <%= @user.email %></h5>
    <h5>Name: <%= @user.name %></h5>
  </div>
</div>

<div class="row">
  <div class="col-md-4", style="width: auto;">
    <%= button_to "Yes", {controller: "users", action: "create", params: params}, class: 'btn btn-success' %>
  </div>
</div>

<div class="row">
  <div class="col-md-4", style="width: auto;">
    <%= button_to "No", {controller: "users", action: "new" }, class: 'btn btn-failure', :method => :get %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign up</h2>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user, :url => { :action => :confirm } do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_group_tag(@user.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
      <% end %>
      <%= form_group_tag(@user.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Sign up", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <br />
      <% avatar_url = @user.avatar_url(128) %>
      <% if avatar_url %>
        <div class="media-left">
          <%= image_tag avatar_url, class: 'media-object' %>
        </div>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading"><%= @user.name %></h2>
        <small>
          <%= pluralize(@user.posts.count, 'post') %>,
          <div class='js-comments-count'><%= pluralize(@user.comments.count, 'comment') %></div>
        </small>
      </div>
    </div>
  </div>
</div>

<h2>Posts</h2>
<% if @user.has_posts? %>
  <%= render @user.posts %>
<% else %>
  <div class="media">
    <%= link_to current_user.name, user_path(current_user) %> has not submitted any posts yet.
  </div>
<% end %>

<h2>Comments</h2>
<% if @user.has_comments? %>
  <%= render @user.comments %>
<% else %>
  <div class="media">
    <%= link_to current_user.name, user_path(current_user) %> has not submitted any comments yet.
  </div>
<% end %>

<h2>Favorites</h2>
<% if @user.has_favorites? %>
    <% @user.favorites.each do |favorite| %>
      <%= render partial: 'users/favorite', locals: { post: favorite.post } %>
    <% end %>
<% else %>
    <div class="media">
      <%= link_to current_user.name, user_path(current_user) %> has not favorited any posts yet.
    </div>
<% end %> 